Repository AY1920S2-CS2103T-W16-2/main, pull requests merged in 2020-04, with the labels that each got.

#107 Add log commands
  src/main/java/seedu/zerotoone/commons/util/DateUtil.java
  src/main/java/seedu/zerotoone/logic/LogicManager.java
  src/main/java/seedu/zerotoone/logic/commands/CommandResult.java
  src/main/java/seedu/zerotoone/logic/commands/ExitCommand.java
  src/main/java/seedu/zerotoone/logic/commands/HelpCommand.java
  src/main/java/seedu/zerotoone/logic/commands/log/DeleteCommand.java
  src/main/java/seedu/zerotoone/logic/commands/log/DisplayCommand.java
  src/main/java/seedu/zerotoone/logic/commands/log/FindCommand.java
  src/main/java/seedu/zerotoone/logic/commands/log/ListCommand.java
  src/main/java/seedu/zerotoone/logic/commands/log/LogCommand.java
  src/main/java/seedu/zerotoone/logic/parser/CliSyntax.java
  src/main/java/seedu/zerotoone/logic/parser/ParserManager.java
  src/main/java/seedu/zerotoone/logic/parser/log/DeleteCommandParser.java
  src/main/java/seedu/zerotoone/logic/parser/log/FindCommandParser.java
  src/main/java/seedu/zerotoone/logic/parser/log/LogCommandParser.java
  src/main/java/seedu/zerotoone/logic/parser/log/LogParserUtil.java
  src/main/java/seedu/zerotoone/model/Model.java
  src/main/java/seedu/zerotoone/model/ModelManager.java
  src/main/java/seedu/zerotoone/model/session/PredicateFilterSessionExerciseName.java
  src/main/java/seedu/zerotoone/storage/session/util/JacksonSessionSet.java
  src/main/java/seedu/zerotoone/ui/MainWindow.java
  src/main/java/seedu/zerotoone/ui/ReportWindow.java
  src/main/java/seedu/zerotoone/ui/views/log/SessionCard.java
  src/main/java/seedu/zerotoone/ui/views/log/SessionSetCard.java
  src/main/java/seedu/zerotoone/ui/views/schedule/ScheduledWorkoutCard.java
  src/main/resources/view/ReportWindow.fxml
  src/main/resources/view/log/SessionCard.fxml
  src/test/java/seedu/zerotoone/logic/commands/CommandResultTest.java
  src/test/java/seedu/zerotoone/logic/commands/ExitCommandTest.java
  src/test/java/seedu/zerotoone/logic/commands/HelpCommandTest.java
  src/test/java/seedu/zerotoone/logic/commands/exercise/CreateCommandTest.java
Labels: type.Task

#108 Update DG as template for feature implementations
  docs/DeveloperGuide.adoc
Labels: documentation

#111 add UML to DG
  docs/DeveloperGuide.adoc
  docs/diagrams/schedule/PopulateSortedScheduledWorkoutList.puml
  docs/diagrams/schedule/ScheduleCreateSequenceDiagram.puml
  docs/images/PopulateSortedScheduledWorkoutList.png
  docs/images/ScheduleCreateSequenceDiagram.png
Labels: documentation

#112 Add documentation to DG for Workout
  docs/DeveloperGuide.adoc
  docs/diagrams/WorkoutManagerClassDiagram.puml
  docs/diagrams/WorkoutManagerSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/WorkoutManagerClassDiagram.png
  docs/images/WorkoutManagerSequenceDiagram.png
Labels: documentation

#113 Edit Exercise's Developer Guide
  docs/DeveloperGuide.adoc
  docs/diagrams/exercise/CreateCommandSequenceDiagram.puml
  docs/images/exercise/CreateCommandSequenceDiagram.png
Labels: documentation

#115 Update User Guide for v1.3
  docs/UserGuide.adoc
  docs/images/UgAddedExerciseSet.png
  docs/images/UgCalendarSchedule.png
  docs/images/UgCreateWorkout.png
  docs/images/UgCreatedExercise.png
  docs/images/UgDoneSet.png
  docs/images/UgExerciseList.png
  docs/images/UgFindExercise.png
  docs/images/UgFindWorkout.png
  docs/images/UgGraphicalLogs.png
  docs/images/UgHelp.png
  docs/images/UgLogList.png
  docs/images/UgMainPage.png
  docs/images/UgScheduleSession.png
  docs/images/UgSkippedSet.png
  docs/images/UgStartWorkout.png
  docs/images/UgUiComponents.png
  docs/images/UgWorkoutList.png
Labels: documentation

#188 Fix Bugs
  build.gradle
  src/main/java/seedu/zerotoone/commons/util/Pair.java
  src/main/java/seedu/zerotoone/commons/util/StringUtil.java
  src/main/java/seedu/zerotoone/logic/commands/exercise/DeleteCommand.java
  src/main/java/seedu/zerotoone/logic/commands/exercise/set/AddCommand.java
  src/main/java/seedu/zerotoone/logic/commands/exercise/set/DeleteCommand.java
  src/main/java/seedu/zerotoone/logic/parser/ParserManager.java
  src/main/java/seedu/zerotoone/model/ModelManager.java
  src/main/java/seedu/zerotoone/model/exercise/ExerciseName.java
  src/main/java/seedu/zerotoone/model/exercise/NumReps.java
  src/main/java/seedu/zerotoone/model/exercise/PredicateFilterExerciseName.java
  src/main/java/seedu/zerotoone/model/exercise/Weight.java
  src/main/java/seedu/zerotoone/model/util/SampleExerciseDataUtil.java
  src/main/java/seedu/zerotoone/model/util/SampleLogDataUtil.java
  src/main/java/seedu/zerotoone/model/util/SampleScheduleDataUtil.java
  src/main/java/seedu/zerotoone/model/util/SampleWorkoutDataUtil.java
  src/main/java/seedu/zerotoone/model/workout/Workout.java
  src/main/java/seedu/zerotoone/model/workout/WorkoutList.java
  src/main/java/seedu/zerotoone/model/workout/WorkoutModel.java
  src/main/java/seedu/zerotoone/ui/CommandBox.java
  src/main/java/seedu/zerotoone/ui/MainWindow.java
  src/main/java/seedu/zerotoone/ui/UiManager.java
  src/test/java/seedu/zerotoone/logic/commands/exercise/CreateCommandTest.java
  src/test/java/seedu/zerotoone/logic/commands/workout/CreateCommandTest.java
  src/test/java/seedu/zerotoone/model/exercise/ExerciseNameTest.java
  src/test/java/seedu/zerotoone/model/exercise/PredicateFilterExerciseNameTest.java
  src/test/java/seedu/zerotoone/testutil/exercise/TypicalExercises.java
  src/test/java/seedu/zerotoone/testutil/workout/TypicalWorkouts.java
Labels: type.Bug

#222 Update user guide with log commands
  docs/UserGuide.adoc
  docs/images/UgGraphicalLogs.png
  docs/images/UgLogList.png
  src/main/java/seedu/zerotoone/logic/Statistics.java
  src/main/java/seedu/zerotoone/model/log/StatisticsData.java
  src/main/java/seedu/zerotoone/ui/StatisticsWindow.java
  src/main/resources/view/StatisticsWindow.fxml
  src/main/resources/view/css/DarkTheme.css
  src/main/resources/view/home/LastSessionCard.fxml
  src/test/java/seedu/zerotoone/model/log/StatisticsDataTest.java
Labels: documentation

#225 Fix Bugs
  src/main/java/seedu/zerotoone/commons/core/Messages.java
  src/main/java/seedu/zerotoone/logic/commands/AboutCommand.java
  src/main/java/seedu/zerotoone/logic/commands/DoneCommand.java
  src/main/java/seedu/zerotoone/logic/commands/SkipCommand.java
  src/main/java/seedu/zerotoone/logic/commands/StartCommand.java
  src/main/java/seedu/zerotoone/logic/commands/StopCommand.java
  src/main/java/seedu/zerotoone/logic/commands/exercise/CreateCommand.java
  src/main/java/seedu/zerotoone/logic/commands/exercise/DeleteCommand.java
  src/main/java/seedu/zerotoone/logic/commands/exercise/EditCommand.java
  src/main/java/seedu/zerotoone/logic/commands/exercise/FindCommand.java
  src/main/java/seedu/zerotoone/logic/commands/exercise/set/AddCommand.java
  src/main/java/seedu/zerotoone/logic/commands/exercise/set/DeleteCommand.java
  src/main/java/seedu/zerotoone/logic/commands/exercise/set/EditCommand.java
  src/main/java/seedu/zerotoone/logic/commands/log/DeleteCommand.java
  src/main/java/seedu/zerotoone/logic/commands/log/FindCommand.java
  src/main/java/seedu/zerotoone/logic/commands/schedule/CreateCommand.java
  src/main/java/seedu/zerotoone/logic/commands/schedule/DeleteCommand.java
  src/main/java/seedu/zerotoone/logic/commands/schedule/EditCommand.java
  src/main/java/seedu/zerotoone/logic/commands/util/Commands.java
  src/main/java/seedu/zerotoone/logic/commands/workout/CreateCommand.java
  src/main/java/seedu/zerotoone/logic/commands/workout/DeleteCommand.java
  src/main/java/seedu/zerotoone/logic/commands/workout/EditCommand.java
  src/main/java/seedu/zerotoone/logic/commands/workout/FindCommand.java
  src/main/java/seedu/zerotoone/logic/commands/workout/exercise/AddCommand.java
  src/main/java/seedu/zerotoone/logic/commands/workout/exercise/DeleteCommand.java
  src/main/java/seedu/zerotoone/logic/commands/workout/exercise/EditCommand.java
  src/main/java/seedu/zerotoone/logic/parser/CliSyntax.java
  src/main/java/seedu/zerotoone/logic/parser/exercise/CreateCommandParser.java
  src/main/java/seedu/zerotoone/logic/parser/exercise/EditCommandParser.java
  src/main/java/seedu/zerotoone/logic/parser/exercise/FindCommandParser.java
  src/main/java/seedu/zerotoone/logic/parser/exercise/set/AddCommandParser.java
  src/main/java/seedu/zerotoone/logic/parser/exercise/set/EditCommandParser.java
  src/main/java/seedu/zerotoone/logic/parser/schedule/CreateCommandParser.java
  src/main/java/seedu/zerotoone/logic/parser/schedule/EditCommandParser.java
  src/main/java/seedu/zerotoone/logic/parser/util/ArgumentTokenizer.java
  src/main/java/seedu/zerotoone/logic/parser/workout/CreateCommandParser.java
  src/main/java/seedu/zerotoone/logic/parser/workout/EditCommandParser.java
  src/main/java/seedu/zerotoone/logic/parser/workout/FindCommandParser.java
  src/main/java/seedu/zerotoone/model/Model.java
  src/main/java/seedu/zerotoone/model/ModelManager.java
  src/main/java/seedu/zerotoone/model/exercise/Weight.java
  src/main/java/seedu/zerotoone/model/workout/Workout.java
  src/main/java/seedu/zerotoone/model/workout/WorkoutList.java
  src/main/java/seedu/zerotoone/model/workout/WorkoutModel.java
  src/test/java/seedu/zerotoone/logic/commands/exercise/EditCommandTest.java
  src/test/java/seedu/zerotoone/logic/parser/util/ArgumentTokenizerTest.java
  src/test/java/seedu/zerotoone/logic/parser/workout/FindCommandParserTest.java
  src/test/java/seedu/zerotoone/testutil/ModelStub.java
Labels: type.Bug

#237 Standardise sample data across tabs
  src/main/java/seedu/zerotoone/model/util/SampleLogDataUtil.java
  src/main/java/seedu/zerotoone/ui/views/log/CompletedExerciseCard.java
  src/main/java/seedu/zerotoone/ui/views/log/CompletedSetCard.java
  src/main/resources/view/log/StatisticsWindow.fxml
Labels: priority.Medium

#248 Add log section to developer guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/log/DataPointAbstractClass.puml
  docs/diagrams/log/DisplayCommandSequenceDiagramPart1.puml
  docs/diagrams/log/DisplayCommandSequenceDiagramPart2.puml
  docs/diagrams/log/LogDateRangeSensibleDefaults.puml
  docs/diagrams/log/StatisticsDataPointsClassDiagram.puml
  docs/diagrams/log/WorkoutSessionDiagram.puml
  docs/images/developer-guide/log/DataPointAbstractClass.png
  docs/images/developer-guide/log/DisplayCommandSequenceDiagramPart1.png
  docs/images/developer-guide/log/DisplayCommandSequenceDiagramPart2.png
  docs/images/developer-guide/log/LogDateRangeSensibleDefaults.png
  docs/images/developer-guide/log/StatisticsDataPointsClassDiagram.png
  docs/images/developer-guide/log/WorkoutSessionDiagram.png
  src/main/java/seedu/zerotoone/logic/commands/util/Commands.java
Labels: documentation
